kind: pipeline
type: docker
name: main
trigger:
  event:
    - push
steps:
  - name: log
    image: alpine
    commands:
      - apk add curl jq
      - export MERGED_FROM_BRANCH=$(./get_merged_branch.sh)
      - '[[ -z $MERGED_FROM_BRANCH ]] && exit'
      - echo "won't be reached if the push is not a pull request merge"
