kind: pipeline
type: docker
name: main
trigger:
  event:
    include:
      - push
      - pull_request
      - tag
      - promote
      - rollback
  # branch:
  #   exclude:
  #     - bidon
  # ref:
  #   include:
  #     - refs/*
steps:
  - name: log
    image: node:alpine
    commands:
      - env | sort
      - ./get_merged_branch.sh
