kind: pipeline
type: docker
name: main
trigger:
  event:
    - push
    - pull_request
    - tag
    - promote
    - rollback
  branch:
    exclude:
      - bidon
  ref:
    include:
      - refs/*
steps:
  - name: build-packages
    image: node:alpine
    commands:
      - env
      - ls
