kind: pipeline
type: docker
name: main
trigger:
  event:
    include:
      - push
      - pull_request
      - tag
      - promote
      - rollback
  # branch:
  #   exclude:
  #     - bidon
  # ref:
  #   include:
  #     - refs/*
steps:
  - name: log
    image: alpine
    commands:
      - apk add curl jq
      - export MERGED_FROM_BRANCH=$(./get_merged_branch.sh)
      - '[[ -z $MERGED_FROM_BRANCH ]] && exit'
      - echo 'ICI'
      - env | sort
